# for local development
# running from base directory: docker-compose -f deploy/docker-compose.yml up --build
version: "3.7"

services:
  rust: &rust
    build:
      context: ../
      dockerfile: deploy/Dockerfile

    environment:
      WEATHER_API_KEY: <your_api_key_on_http://api.weatherapi.com>

    ports:
      - "8080:8080"

    command: cargo run
